### ISSUE TITLE
Add more contributor information for @reallinfo

### ISSUE THREAD

**Issue by mcb2003** [mcb2003/blind-computing#16]
Recently, @reallinfo submitted to the blind computing project a very nice logo. This logo has now been integrated into the site, at least on the home page and hopefully in other places in the future. I then added reallinfo to the contributors list on the site. However, just going off their github profile, I have very little information to fill in. Really the only things in the contributors table about @reallinfo is their username and github link. If you are reading this reallinfo and if you could help me out by providing me with information to add to your profile, either as a reply, or as a pull request to the [mysql-file branch](https://github.com/blind-computing/blind-computing/tree/mysql-file), the information, all optional, I can use is:
* Full name
* Description / Bio
* Twitter handle
* YouTube channel.
* Discord handle (with or without the 4 digit number)
* Email address
* Github (I already have this).
* Link to a profile picture

_Mikey_

**Comment by reallinfo** [comment]
thank you very much but  I'm not active on other platforms except github. If you need something about design, you can reach me via gmail address. 

komiserback@gmail.com
