### ISSUE TITLE
Fix an issue on video pages where the video info is displayed below the video and not to the right of it

### ISSUE THREAD

**Issue by mcb2003** [mcb2003/blind-computing#3]
As far as I’m aware, I’ve set all of the CSS up correctly and everything looks good in the code, however, at least in Firefox on a 1080p display, the video information is displayed below the video itself and not to the right of it like it used to be.

**Comment by mcb2003** [comment]
@billyLapworth maybe you could help with this?

**Comment by BillyLapworth** [comment]
@mcb2003 I’ll try.

**Comment by mcb2003** [comment]
Just to clarify, this is what it looks like currently.

![blind-computing-screenshot](https://user-images.githubusercontent.com/7888860/38166033-cda730d6-3514-11e8-9a85-15136c1975de.png)

**Comment by BillyLapworth** [comment]
Have you given the video the '**float: left**' property?

**Comment by mcb2003** [comment]
@billyLapworth Checking right now.

**Comment by mcb2003** [comment]
I've added the __.video-embed__ class to the __<iframe>__ object, which is styled like the following

    .video-embed {
    display:inline block;
    overflow:show;
    max-width:60%;
    width:640px;
    height:480px;
    float:left;
    }

This is the CSS for the __.video-info__ class that's applied to the __<aside>__ object responsible for the info:

    .video-info {
    display:inline block;
    float:right;
    min-width:25%;
    width:30%;
    }

_mikey_

**Comment by mcb2003** [comment]
Think I've fixed it!

For some reason, the `<iframe>` object doesn't allow a CSS class to be applied, namely the __.video-embed__ class. I fixed this by adding the CSS inline:
```html
<iframe ... style="float:right;display:inline;..." ...>
```

**Comment by mcb2003** [comment]
Okay... Turns out I was just missing your bracket.
